#!/bin/bash
main() {
    if [ -z "$*" ]; then
        echo "please give post name"
    else
        $(add_comment_section "$@")
    fi
}
add_comment_section() {
    touch src/posts/$1.md
cat > src/posts/$1.md <<EOF
---
title:
description:
date:
tags:
---

<p id="lastUpdated-css">Updated on <span id="lastUpdated"></span></p>

<hr>
<script src="https://utteranc.es/client.js"
        repo="Dark-Matter7232/Dark-Matter7232.github.io"
        issue-term="pathname"
        theme="github-dark-orange"
        crossorigin="anonymous"
        async>
</script>
EOF
}

main "$@"
